# Generated by Django 2.2 on 2021-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Blog name')),
                ('content', models.CharField(max_length=5000000, verbose_name='Blog content')),
                ('comment', models.CharField(max_length=200, verbose_name='Blog comment')),
            ],
        ),
    ]
