# Generated by Django 2.2 on 2021-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211030_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
