# Generated by Django 2.2 on 2021-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211030_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.CharField(default='', max_length=200, verbose_name='Blog comment'),
        ),
    ]
